services:
  elasticsearch:
    image: elasticsearch:9.0.2
    ports:
      - 9200:9200
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      ELASTIC_PASSWORD: "password"
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
    healthcheck:
      test: curl -s http://localhost:9200 || exit 1
      interval: 5s
      retries: 10

  kibana:
    image: kibana:9.0.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch
